let readlineSync = require('readline-sync');
let primerIngrediente = readlineSync.question("Por favor ingrese el primer ingrediente: ");
console.log("el primer ingrediente es:", primerIngrediente);
let segundoIngrediente = readlineSync.question("Por favor ingrese el segundo ingrediente: ");
console.log("el segundo ingrediente es:", segundoIngrediente);
let tercerIngrediente = readlineSync.question("Por favor ingrese el tercer ingrediente: ");
console.log("el tercer ingrediente es:", tercerIngrediente);
let cuartoIngrediente = readlineSync.question("Por favor ingrese el cuarto ingrediente: ");
console.log("el cuarto ingrediente es:", cuartoIngrediente);
let quintoIngrediente = readlineSync.question("Por favor ingrese el quinto ingrediente: ");
console.log("el quinto ingrediente es:", quintoIngrediente);
let sextoIngrediente = readlineSync.question("Por favor ingrese el sexto ingrediente: ");
console.log("el sexto ingrediente es: ", sextoIngrediente);
let septimoIngrediente = readlineSync.question("Por favor ingrese el septimo ingrediente: ");
console.log("el septimo ingrediente es: ", septimoIngrediente);
let octavoIngrediente = readlineSync.question("Por favor ingrese el octavo ingrediente: ");
console.log("el octavo ingrediente es: ",octavoIngrediente);