let readlineSync = require('readline-sync');
let primerIngrediente = readlineSync.question("Por favor ingrese el primer ingrediente: ");
let segundoIngrediente = readlineSync.question("Por favor ingrese el segundo ingrediente: ");
let tercerIngrediente = readlineSync.question("Por favor ingrese el tercer ingrediente: ");
let cuartoIngrediente = readlineSync.question("Por favor ingrese el cuarto ingrediente: ");
let quintoIngrediente = readlineSync.question("Por favor ingrese el quinto ingrediente: ");
let sextoIngrediente = readlineSync.question("Por favor ingrese el sexto ingrediente: ");
let septimoIngrediente = readlineSync.question("Por favor ingrese el septimo ingrediente: ");
let octavoIngrediente = readlineSync.question("Por favor ingrese el octavo ingrediente: ");
let primerRecipiente = readlineSync.question("Por favor ingrese el primer recipiente: ");
let segundoRecipiente = readlineSync.question("Por favor ingrese el segundo recipiente: ");
console.log("el primer ingrediente es:", primerIngrediente);
console.log("el segundo ingrediente es:", segundoIngrediente);
console.log("el tercer ingrediente es:", tercerIngrediente);
console.log("el cuarto ingrediente es:", cuartoIngrediente);
console.log("el quinto ingrediente es:", quintoIngrediente);
console.log("el sexto ingrediente es: ", sextoIngrediente);
console.log("el septimo ingrediente es: ", septimoIngrediente);
console.log("el octavo ingrediente es: ", octavoIngrediente);
console.log("el primer recipiente es: ", primerRecipiente);
console.log("el segundo recipiente es: ", segundoRecipiente);